spring:
  application:
    name: monew
  datasource:
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics